apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infisical-pki-issuer.fullname" . }}-controller-manager
  labels:
  {{- include "infisical-pki-issuer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
