# permissions for end users to view clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infisical-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-viewer-role
rules:
- apiGroups:
  - infisical-issuer.infisical.com
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infisical-issuer.infisical.com
  resources:
  - clusterissuers/status
  verbs:
  - get
