apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-issuer
spec:
  commonName: certificate-by-issuer.example.com
  secretName: certificate-by-issuer
  issuerRef:
    name: issuer-infisical
    group: infisical-issuer.infisical.com
    kind: Issuer
  privateKey:
    algorithm: ECDSA
    size: 256
