# NOTE (dangtony98): necessary permissions for cert-manager to work with Infisical issuers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infisical-issuer-approver
rules:
  # Permission to approve or deny CertificateRequests for signers in cert-manager.io API group
  - apiGroups: ['cert-manager.io']
    resources: ['signers']
    verbs: ['approve']
    resourceNames:
      # Grant approval permissions for namespaced issuers
      - "issuers.infisical-issuer.infisical.com/default.issuer-infisical"
      # Grant approval permissions for cluster-scoped issuers
      - "clusterissuers.infisical-issuer.infisical.com/clusterissuer-infisical"
---
# Bind the cert-manager service account to the new role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-issuer-approver-binding
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infisical-issuer-approver