apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-clusterissuer
spec:
  commonName: certificate-by-clusterissuer.infisical.com
  secretName: certificate-by-clusterissuer
  issuerRef:
    name: clusterissuer-infisical
    group: infisical-issuer.infisical.com
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
