apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-clusterissuer
spec:
  commonName: certificate-by-clusterissuer.example.com
  secretName: certificate-by-clusterissuer
  issuerRef:
    name: clusterissuer-sample
    group: sample-issuer.example.com
    kind: ClusterIssuer
