apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-issuer
  namespace: default
spec:
  commonName: certificate-by-issuer.infisical.com
  secretName: certificate-by-issuer
  issuerRef:
    name: issuer-infisical
    group: infisical-issuer.infisical.com
    kind: Issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 48h
  renewBefore: 12h
