apiVersion: v1
kind: Secret
metadata:
  name: clusterissuer-infisical-client-secret
  namespace: infisical-issuer-system
data:
  clientSecret: MjUyZGI3NDU1ZTNkNTFjNzY0MWYyZGY5NjZiOTdiMzMxMThmZmE0NDE0NDBhOGQ5Yjc3YTYyNzIyYjZlNTAxNg==
